server:
  port: 8010
  servlet:
    session:
      timeout: 10
  tomcat:
    uri-encoding: UTF-8
    
logging:
  level:
    root: INFO

spring:
  application:
    name: Movie  

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:pwd123@eureka-primary:8771/eureka/ 
  instance:
    #hostname: movie-service
    metadata-map:
      # 自定义元数据
      my-metadata: Movie自定义元数据
    
user:
  serviceUrl: http://localhost:8000/
  
